# -*- coding: utf-8 -*-
"""factorialRecursivo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YGksQVtTOtUd9dcbwwV1PEEJUIUTh9S
"""
print("Rosario Rodriguez Moreno")
class FactorialCalculator:
    def __init__(self, number):
        """
        Inicializa la clase con un número entero positivo.

        :param number: número del cual se desea calcular el factorial
        """
        self.number = number

    def calculate(self):
        """
        Método público que inicia el cálculo del factorial.

        :return: factorial del número
        """
        return self._factorial_recursive(self.number)

    def _factorial_recursive(self, n):
        """
        Método recursivo privado para calcular el factorial.

        :param n: número actual en la recursión
        :return: factorial de n
        """
        if n == 1:
            return 1
        else:
            return n * self._factorial_recursive(n - 1)


# Ejemplo de uso:
calc = FactorialCalculator(5)
print(calc.calculate())  # Salida: 120